name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Karim!"
      - name: Print goodbye
        run: echo "WF Completed - bye!"
