name: First-workflow
on: workflow_dispatch
jobs:
  first-job:
    run-on: ubuntu-latest
      steps:
        - name: Print Greeting
          run: echo "First Run"
        - Name : Good Bye
          run: echo "Run completed"
